[package]
name = "asciimusic"
description = "Simple and fun, but largely useless, program and library for processing a base32-based text format to audio output"
license = "MIT"
readme = "README.md"
version = "0.1.3"
authors = ["Taylor C. Richberger <taywee@gmx.com>"]
edition = "2018"
documentation = "https://docs.rs/asciimusic"
homepage = "https://gitlab.com/Taywee/asciimusic"
repository = "https://gitlab.com/Taywee/asciimusic"
keywords = ["music", "audio", "musicxml"]
categories = ["multimedia::audio"]
default-run = "asciimusic"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
