[package]
name = "asciimusic"
description = "Simple and fun, but largely useless, program and library for processing a base32-based text format to audio output"
license = "MIT"
readme = "README.md"
version = "0.1.1"
authors = ["Taylor C. Richberger <taywee@gmx.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
